"""PDF generation for the HaMuzim legal exhibit export.

Uses reportlab (pure-python, no system dependencies) so it installs cleanly
on Windows without the GTK/cairo stack that weasyprint requires.
"""

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

CONFIDENCE_COLORS = {
    "high": colors.HexColor("#1a7f37"),
    "medium": colors.HexColor("#9a6700"),
    "low": colors.HexColor("#cf222e"),
}


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Oblique", 7.5)
    canvas.setFillColor(colors.HexColor("#555555"))
    text = (
        "Generated by HaMuzim. All sources cited. This report is an "
        "evidentiary exhibit, not a legal determination."
    )
    canvas.drawCentredString(A4[0] / 2, 14 * mm, text)
    canvas.drawRightString(A4[0] - 18 * mm, 14 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_exhibit_pdf(parcel: dict, observations: list, summary: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=24 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        title="HaMuzim Spatial Evidence Report",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "HaMuzimTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#111111"),
        spaceAfter=2,
    )
    subtitle_style = ParagraphStyle(
        "HaMuzimSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#555555"),
        spaceAfter=14,
    )
    h2_style = ParagraphStyle(
        "HaMuzimH2",
        parent=styles["Heading2"],
        fontSize=13,
        spaceBefore=14,
        spaceAfter=6,
        textColor=colors.HexColor("#111111"),
    )
    body_style = ParagraphStyle(
        "HaMuzimBody",
        parent=styles["Normal"],
        fontSize=9.5,
        leading=13,
    )
    summary_style = ParagraphStyle(
        "HaMuzimSummary",
        parent=styles["Normal"],
        fontSize=10,
        leading=14.5,
        backColor=colors.HexColor("#f4f4f4"),
        borderPadding=8,
    )

    story = []
    story.append(Paragraph("HaMuzim Spatial Evidence Report", title_style))
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph(f"Generated {generated}", subtitle_style))

    # Parcel coordinates
    story.append(Paragraph("Parcel", h2_style))
    story.append(Paragraph(f"<b>Name:</b> {parcel.get('name', 'Demo Parcel')}", body_style))
    coord_lines = "<br/>".join(
        f"{i + 1}. {lon:.5f}, {lat:.5f}" for i, (lon, lat) in enumerate(parcel.get("coordinates", []))
    )
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"<b>Boundary vertices (lon, lat):</b><br/>{coord_lines}", body_style))

    # Observation table
    story.append(Paragraph("Observation Record", h2_style))
    table_data = [["Year", "Source", "Type", "Finding", "Confidence"]]
    for obs in observations:
        table_data.append(
            [
                str(obs["year"]),
                obs["source"],
                obs["type"],
                Paragraph(obs["finding"], body_style),
                obs["confidence"].upper(),
            ]
        )

    table = Table(
        table_data,
        colWidths=[13 * mm, 34 * mm, 20 * mm, 78 * mm, 24 * mm],
        repeatRows=1,
    )
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111111")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f7f7")]),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for i, obs in enumerate(observations, start=1):
        c = CONFIDENCE_COLORS.get(obs["confidence"], colors.black)
        style_cmds.append(("TEXTCOLOR", (4, i), (4, i), c))
        style_cmds.append(("FONTNAME", (4, i), (4, i), "Helvetica-Bold"))
    table.setStyle(TableStyle(style_cmds))
    story.append(table)

    # AI Summary
    story.append(Paragraph("AI Summary", h2_style))
    story.append(Paragraph(summary, summary_style))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
