"""PDF generation for the HaMuzim legal exhibit export.

Uses reportlab (pure-python, no system dependencies) so it installs cleanly
on Windows without the GTK/cairo stack that weasyprint requires.
"""

import io
import os
import re
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Global Fonts config
FONT_NAME = "Helvetica"
FONT_BOLD_NAME = "Helvetica-Bold"
FONT_ITALIC_NAME = "Helvetica-Oblique"

# Check for Windows Arial font to support Hebrew Unicode
arial_path = r"C:\Windows\Fonts\arial.ttf"
arial_bold_path = r"C:\Windows\Fonts\arialbd.ttf"
arial_italic_path = r"C:\Windows\Fonts\ariali.ttf"

if os.path.exists(arial_path):
    try:
        pdfmetrics.registerFont(TTFont("Arial", arial_path))
        FONT_NAME = "Arial"
        if os.path.exists(arial_bold_path):
            pdfmetrics.registerFont(TTFont("Arial-Bold", arial_bold_path))
            FONT_BOLD_NAME = "Arial-Bold"
        else:
            FONT_BOLD_NAME = "Arial"
        if os.path.exists(arial_italic_path):
            pdfmetrics.registerFont(TTFont("Arial-Italic", arial_italic_path))
            FONT_ITALIC_NAME = "Arial-Italic"
        else:
            FONT_ITALIC_NAME = "Arial"
    except Exception:
        pass

CONFIDENCE_COLORS = {
    "high": colors.HexColor("#1a7f37"),
    "medium": colors.HexColor("#9a6700"),
    "low": colors.HexColor("#cf222e"),
}

TRANSLATIONS = {
    "en": {
        "title": "HaMuzim Spatial Evidence Report",
        "generated": "Generated",
        "parcel": "Parcel",
        "name": "Name",
        "boundary_vertices": "Boundary vertices (lon, lat)",
        "observation_record": "Observation Record",
        "table_year": "Year",
        "table_source": "Source",
        "table_type": "Type",
        "table_finding": "Finding",
        "table_confidence": "Confidence",
        "ai_summary": "AI Summary",
        "footer_text": "Generated by HaMuzim. All sources cited. This report is an evidentiary exhibit, not a legal determination.",
        "page": "Page",
    },
    "he": {
        "title": "דו\"ח ראיות מרחבי של המוזים",
        "generated": "הופק ב-",
        "parcel": "חלקה",
        "name": "שם",
        "boundary_vertices": "קודקודי גבול (קו אורך, קו רוחב)",
        "observation_record": "רשומת תצפיות",
        "table_year": "שנה",
        "table_source": "מקור",
        "table_type": "סוג",
        "table_finding": "ממצא",
        "table_confidence": "רמת ביטחון",
        "ai_summary": "סיכום בינה מלאכותית",
        "footer_text": "הופק על ידי המוזים. כל המקורות מצוטטים. דו\"ח זה מהווה מוצג ראייתי, ולא קביעה משפטית.",
        "page": "עמוד",
    }
}


def swap_braces(text: str) -> str:
    res = []
    for c in text:
        if c == '(': res.append(')')
        elif c == ')': res.append('(')
        elif c == '[': res.append(']')
        elif c == ']': res.append('[')
        elif c == '{': res.append('}')
        elif c == '}': res.append('{')
        else: res.append(c)
    return "".join(res)


def reverse_hebrew_word(word: str) -> str:
    return swap_braces(word[::-1])


def reverse_text_segment(text: str) -> str:
    tokens = re.split(r'(\s+)', text)
    processed = []
    for token in tokens:
        if re.search(r'[\u0590-\u05ff]', token):
            processed.append(reverse_hebrew_word(token))
        else:
            processed.append(token)
    return "".join(processed[::-1])


def reverse_bidi(text: str) -> str:
    if not text:
        return ""
    if not any('\u0590' <= c <= '\u05ff' for c in text):
        return text
    tokens = re.split(r'(<[^>]+>)', text)
    result_tokens = []
    for token in tokens:
        if token.startswith('<') and token.endswith('>'):
            result_tokens.append(token)
        else:
            result_tokens.append(reverse_text_segment(token))
    return "".join(result_tokens)


def _footer(canvas, doc, lang="en"):
    canvas.saveState()
    canvas.setFont(FONT_ITALIC_NAME, 7.5)
    canvas.setFillColor(colors.HexColor("#555555"))
    
    t = TRANSLATIONS.get(lang, TRANSLATIONS["en"])
    footer_text = reverse_bidi(t["footer_text"])
    page_text = reverse_bidi(f"{t['page']} {doc.page}")
    
    if lang == "he":
        canvas.drawCentredString(A4[0] / 2, 14 * mm, footer_text)
        canvas.drawString(18 * mm, 14 * mm, page_text)
    else:
        canvas.drawCentredString(A4[0] / 2, 14 * mm, footer_text)
        canvas.drawRightString(A4[0] - 18 * mm, 14 * mm, page_text)
    canvas.restoreState()


def build_exhibit_pdf(parcel: dict, observations: list, summary: str, lang: str = "en") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=24 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        title="HaMuzim Spatial Evidence Report",
    )

    t = TRANSLATIONS.get(lang, TRANSLATIONS["en"])
    align = TA_RIGHT if lang == "he" else TA_LEFT

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "HaMuzimTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#111111"),
        spaceAfter=2,
        fontName=FONT_BOLD_NAME,
        alignment=align,
    )
    subtitle_style = ParagraphStyle(
        "HaMuzimSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#555555"),
        spaceAfter=14,
        fontName=FONT_NAME,
        alignment=align,
    )
    h2_style = ParagraphStyle(
        "HaMuzimH2",
        parent=styles["Heading2"],
        fontSize=13,
        spaceBefore=14,
        spaceAfter=6,
        textColor=colors.HexColor("#111111"),
        fontName=FONT_BOLD_NAME,
        alignment=align,
    )
    body_style = ParagraphStyle(
        "HaMuzimBody",
        parent=styles["Normal"],
        fontSize=9.5,
        leading=13,
        fontName=FONT_NAME,
        alignment=align,
    )
    summary_style = ParagraphStyle(
        "HaMuzimSummary",
        parent=styles["Normal"],
        fontSize=10,
        leading=14.5,
        backColor=colors.HexColor("#f4f4f4"),
        borderPadding=8,
        fontName=FONT_NAME,
        alignment=align,
    )

    story = []
    story.append(Paragraph(reverse_bidi(t["title"]), title_style))
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph(reverse_bidi(f"{t['generated']} {generated}"), subtitle_style))

    # Parcel coordinates
    story.append(Paragraph(reverse_bidi(t["parcel"]), h2_style))
    story.append(Paragraph(reverse_bidi(f"<b>{t['name']}:</b> {parcel.get('name', 'Demo Parcel')}"), body_style))
    coord_lines = "<br/>".join(
        f"{i + 1}. {lon:.5f}, {lat:.5f}" for i, (lon, lat) in enumerate(parcel.get("coordinates", []))
    )
    story.append(Spacer(1, 4))
    story.append(Paragraph(reverse_bidi(f"<b>{t['boundary_vertices']}:</b><br/>{coord_lines}"), body_style))

    # Observation table
    story.append(Paragraph(reverse_bidi(t["observation_record"]), h2_style))
    
    headers = [
        reverse_bidi(t["table_year"]),
        reverse_bidi(t["table_source"]),
        reverse_bidi(t["table_type"]),
        reverse_bidi(t["table_finding"]),
        reverse_bidi(t["table_confidence"])
    ]
    col_widths = [13 * mm, 34 * mm, 20 * mm, 78 * mm, 24 * mm]
    
    table_data = [headers]
    for obs in observations:
        table_data.append(
            [
                reverse_bidi(str(obs["year"])),
                reverse_bidi(obs["source"]),
                reverse_bidi(obs["type"]),
                Paragraph(reverse_bidi(obs["finding"]), body_style),
                reverse_bidi(obs["confidence"].upper()),
            ]
        )

    if lang == "he":
        # Reverse columns for RTL
        table_data = [row[::-1] for row in table_data]
        col_widths = col_widths[::-1]

    table = Table(
        table_data,
        colWidths=col_widths,
        repeatRows=1,
    )
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111111")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 0), (-1, 0), FONT_BOLD_NAME),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f7f7")]),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for i, obs in enumerate(observations, start=1):
        c = CONFIDENCE_COLORS.get(obs["confidence"], colors.black)
        col_idx = 0 if lang == "he" else 4
        style_cmds.append(("TEXTCOLOR", (col_idx, i), (col_idx, i), c))
        style_cmds.append(("FONTNAME", (col_idx, i), (col_idx, i), FONT_BOLD_NAME))
    table.setStyle(TableStyle(style_cmds))
    story.append(table)

    # AI Summary
    story.append(Paragraph(reverse_bidi(t["ai_summary"]), h2_style))
    story.append(Paragraph(reverse_bidi(summary), summary_style))

    doc.build(story, onFirstPage=lambda c, d: _footer(c, d, lang), onLaterPages=lambda c, d: _footer(c, d, lang))
    return buf.getvalue()

